//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContact.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Domains = new HashSet<Domain>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int StateId { get; set; }
        public int CountryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Domain> Domains { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual Country Country { get; set; }
    }
}
