//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContact.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Domains = new HashSet<Domain>();
            this.States = new HashSet<State>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.Cities = new HashSet<City>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<Domain> Domains { get; set; }
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<City> Cities { get; set; }
    }
}
