//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContact.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domain
    {
        public Domain()
        {
            this.DomainGroupUsers = new HashSet<DomainGroupUser>();
            this.WorkingGroups = new HashSet<WorkingGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string Address { get; set; }
        public int City { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual ICollection<DomainGroupUser> DomainGroupUsers { get; set; }
        public virtual ICollection<WorkingGroup> WorkingGroups { get; set; }
    }
}
