//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContact.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public string Context { get; set; }
        public string Field { get; set; }
        public int ContextId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangedBy { get; set; }
    }
}
