//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContact.Entities
{
    using System;
    using System.Collections.Generic;
    using CustomAttributes;
    
    public partial class Issue
    {
        public int Id { get; set; }
        [RequiredForJson]
        public string IssueSubject { get; set; }
        [RequiredForJson]
        public string IssueDetails { get; set; }
        [RequiredForJson]
        public int AssignedTo { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
