//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContact.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserId { get; set; }
        public string DisplayName { get; set; }
        public int DomainId { get; set; }
        public string Address { get; set; }
        public int City { get; set; }
        public string Zip { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual City City2 { get; set; }
        public virtual User User { get; set; }
    }
}
