//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContact.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingGroup
    {
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string EmailId { get; set; }
        public int DomainId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Domain Domain { get; set; }
    }
}
